"""latest

Revision ID: efd7b473af66
Revises: 6c6e29c08274
Create Date: 2026-06-27 13:01:11.810821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'efd7b473af66'
down_revision = '6c6e29c08274'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###